### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MaksimTrofimov** [MaksimTrofimov/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by clonemy** [comment]
<h2>Résumé</h2>
<p>— Hello! I am a developer with 2+ years experience in PHP. I am a loyal and communicative person and can easily work as a team or alone in a project.
</p>
