### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by MaksimTrofimov** [MaksimTrofimov/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by clonemy** [comment]
<h3>Experience</h3>
<p>20 July 2017 – 29 February 2020</p>
<p>PHP Developer at Soft Company</p>
<ul>
<li>Participating in the entire application lifecycle, focusing on coding and debugging</li>
<li>Troubleshooting and debug applications at all stages</li>
<li>Collaborating with Front-end developers to integrate user-facing elements with server side logic</li>
<li>Support of existing projects</li>
</ul>
