### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by MaksimTrofimov** [MaksimTrofimov/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by clonemy** [comment]
<h3>Skills</h3>
<p>PHP KOHANA HTML CSS JS JQUERY LINUX WINDOWS GIT</p>
<h3>LIKES</h3>
<p>LIFE FAMILY SWEET CATS FRIENDSHIP HUMOR SPRING PROGRAMMING READ TRAINING FANTASY SCIENCE NATURE MUSIC TRAVEL MY CITY PEOPLE SUN BEACH SEA
</p>
<h3>DISLIKES</h3>
<p>COLD, INDIFFERENCE, TIES, DENTISTS, LIES<p/>
<h3>WANTS</h3>
<p>BE A PROFESSIONAL STUDY DEVELOP BE A HEALTHY AND STRONG PERSON TO TRAVEL FLY ON MARS LIVE FOREVER</p>
<h3>EDUCATION</h3>
<p>December 2016 –  May 2017 </p>
<p>A-Level "PHP advance "   Kharkiv, Ukraine</p>
<p>September 1999 –  June 2004</p>
<p>Kharkiv National University of Radio Electronics</p>
